config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create ]
  end
  resources :bookmarks, only: [ :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, presence: true, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 5 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true
  has_one_attached :photo
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = List.find(params[:list_id])
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie])
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
      if @list.save
        redirect_to list_path(@list)
      else
        render :new
      end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end


  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="h1-nouveau-bookmark">
    <h1 class="nouveau-bookmark"> Nouveau Bookmarks</h1>
  </div>
    <%= simple_form_for [ @list, @bookmark ] do |f| %>
      <%= f.input :comment %>
      <%= f.input :movie, collection: Movie.all %>
      <%= f.button :submit,  class: "btn btn-dark" %>
    <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WATCHList2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="h1-index-list">
    <h1 class="liste-des-films">Liste des styles de films</h1>
  </div>

  <div class="div-de-la-photo-et-du-nom-de-la-liste">
    <% @lists.each do |list| %>
        <%= link_to list_path(list), class:'link-index' do %>
        <div class="photos-and-name-list">
          <div class="nom-de-la-liste-index">
            <strong>
            <%= list.name %>
            </strong>
          </div>
            <%= cl_image_tag list.photo.key, class:"image-list"%>
            <div class="bouton-supprimer-index">
              <%= link_to "Supprimer la liste",
                list_path(list),
                method: :delete,
                data: { confirm: "Are you sure?"},
                class:"btn btn-dark" %>
              </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

  <div class="creation-de-la-liste">
    <%= link_to "Créez une nouvelle liste", new_list_path, class: "btn btn-dark" %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="h1-nouvelle-liste">
    <h1 class="nouvelle-liste">Nouvelle Liste </h1>
  </div>
  <div class="formulaire-div-parente">
    <div class="formulaire-new-list">
      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Valider",class: "bouton-de-formulaire-liste"%>
        <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="h1-show-list">
    <h1 class="show-du-films">Voici les films </h1>
  </div>

   <div class="row d-flex justify-content-center">
      <div class="col-sm-12 col-md-3">
        <%= @list.name %>
          <%= cl_image_tag @list.photo.key, class: "d-block w-100" %>
      </div>
  </div>

    <div class="row d-flex justify-content-center">
      <div class="bookmarks-all">
          <% @list.bookmarks.each do |bookmark| %>
            <%= bookmark.comment %>
            <%= link_to "Supprimer",
              bookmark_path(bookmark),
              method: :delete,
              data: { confirm: "Are you sure?"},
              class:"btn btn-dark" %>
          <% end %>
      </div>
    </div>
    <div class="row d-flex justify-content-center">
      <div class="aller-sur-la-creation-d1-avis">
        <%= link_to "Rédigez un avis",
           new_list_bookmark_path(@list),
           class:"btn btn-dark"
         %>
      </div>
    </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>